plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.vetplan011_wq.twa'
    compileSdk 36

    defaultConfig {
        applicationId 'io.github.vetplan011_wq.twa'
        minSdk 23
        targetSdk 36
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
}
